alter table public.project_quotes
  add column if not exists revision_number integer not null default 0,
  add column if not exists revision_of_quote_id bigint references public.project_quotes(id) on delete set null,
  add column if not exists revision_notes text,
  add column if not exists is_current_revision boolean not null default true,
  add column if not exists superseded_at timestamptz;

create index if not exists project_quotes_revision_family_idx
  on public.project_quotes (coalesce(revision_of_quote_id, id), revision_number desc);

alter table public.projects
  add column if not exists next_action_owner text,
  add column if not exists next_action_due date,
  add column if not exists blocked_reason_category text,
  add column if not exists blocked_details text,
  add column if not exists customer_signoff_at timestamptz,
  add column if not exists customer_signoff_by text,
  add column if not exists final_photos_confirmed boolean not null default false,
  add column if not exists warranty_expires_at date;

alter table public.projects drop constraint if exists projects_blocked_reason_category_check;
alter table public.projects add constraint projects_blocked_reason_category_check check (
  blocked_reason_category is null or blocked_reason_category in (
    'Waiting on Customer', 'Waiting on Material', 'Waiting on Design',
    'Waiting on Payment', 'Waiting on Site Access', 'Equipment Problem',
    'Scheduling Conflict', 'Other'
  )
);

create table if not exists public.project_change_orders (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  change_order_number text not null,
  title text not null,
  description text,
  reason text,
  amount_delta numeric(12,2) not null default 0,
  schedule_days_delta integer not null default 0,
  status text not null default 'Draft' check (status in ('Draft', 'Sent', 'Approved', 'Declined', 'Cancelled')),
  customer_approval_name text,
  customer_approved_at timestamptz,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, change_order_number)
);

create table if not exists public.project_communications (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  communication_type text not null check (communication_type in ('Phone Call', 'Email', 'Text Message', 'Meeting', 'Site Conversation', 'Other')),
  direction text not null default 'Outgoing' check (direction in ('Incoming', 'Outgoing', 'Internal')),
  contact_name text,
  subject text,
  summary text not null,
  follow_up_required boolean not null default false,
  follow_up_due date,
  follow_up_completed_at timestamptz,
  recorded_by text,
  created_at timestamptz not null default now()
);

create index if not exists project_change_orders_project_idx on public.project_change_orders (project_id, created_at desc);
create index if not exists project_communications_project_idx on public.project_communications (project_id, created_at desc);
create index if not exists project_communications_follow_up_idx on public.project_communications (follow_up_required, follow_up_due) where follow_up_completed_at is null;

alter table public.project_change_orders enable row level security;
alter table public.project_communications enable row level security;

grant select, insert, update, delete on public.project_change_orders to authenticated;
grant select, insert, update, delete on public.project_communications to authenticated;
grant usage, select on sequence public.project_change_orders_id_seq to authenticated;
grant usage, select on sequence public.project_communications_id_seq to authenticated;
revoke all on public.project_change_orders from anon;
revoke all on public.project_communications from anon;

drop policy if exists "Active employees can manage project change orders" on public.project_change_orders;
create policy "Active employees can manage project change orders"
  on public.project_change_orders for all to authenticated
  using (exists (select 1 from public.employee_profiles ep where ep.auth_user_id = (select auth.uid()) and ep.is_active = true))
  with check (exists (select 1 from public.employee_profiles ep where ep.auth_user_id = (select auth.uid()) and ep.is_active = true));

drop policy if exists "Active employees can manage project communications" on public.project_communications;
create policy "Active employees can manage project communications"
  on public.project_communications for all to authenticated
  using (exists (select 1 from public.employee_profiles ep where ep.auth_user_id = (select auth.uid()) and ep.is_active = true))
  with check (exists (select 1 from public.employee_profiles ep where ep.auth_user_id = (select auth.uid()) and ep.is_active = true));
