create table if not exists public.project_units (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  unit_name text not null,
  unit_number text,
  description text,
  stage text not null default 'Planning',
  status text not null default 'Not Started',
  handoff_status text not null default 'Not Ready',
  handoff_method text not null default 'Customer Pickup',
  scheduled_handoff_at timestamptz,
  completed_at timestamptz,
  assigned_to text,
  notes text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_units_stage_check check (stage in (
    'Planning', 'Design', 'Materials', 'Fabrication', 'Finish',
    'Final Inspection', 'Ready for Pickup / Delivery', 'Completed'
  )),
  constraint project_units_status_check check (status in (
    'Not Started', 'Ready', 'In Progress', 'Blocked', 'Complete'
  )),
  constraint project_units_handoff_status_check check (handoff_status in (
    'Not Ready', 'Waiting for Customer Pickup', 'Pickup Scheduled', 'Picked Up',
    'Delivery Scheduled', 'Delivered', 'Not Required'
  )),
  constraint project_units_handoff_method_check check (handoff_method in (
    'Customer Pickup', 'Metal Worx Delivery', 'Third-Party Delivery', 'Not Required'
  ))
);

create index if not exists project_units_project_sort_idx
  on public.project_units(project_id, is_active, sort_order, id);
create index if not exists project_units_handoff_idx
  on public.project_units(handoff_status, scheduled_handoff_at)
  where is_active = true;

alter table public.project_units enable row level security;

grant select, insert, update on public.project_units to authenticated;
grant usage, select on sequence public.project_units_id_seq to authenticated;
revoke all on public.project_units from anon;

drop policy if exists "Active employees can view project units" on public.project_units;
create policy "Active employees can view project units"
on public.project_units for select
to authenticated
using (
  exists (
    select 1 from public.employee_profiles employee
    where employee.auth_user_id = (select auth.uid())
      and employee.is_active = true
  )
);

drop policy if exists "Active employees can create project units" on public.project_units;
create policy "Active employees can create project units"
on public.project_units for insert
to authenticated
with check (
  exists (
    select 1 from public.employee_profiles employee
    where employee.auth_user_id = (select auth.uid())
      and employee.is_active = true
  )
);

drop policy if exists "Active employees can update project units" on public.project_units;
create policy "Active employees can update project units"
on public.project_units for update
to authenticated
using (
  exists (
    select 1 from public.employee_profiles employee
    where employee.auth_user_id = (select auth.uid())
      and employee.is_active = true
  )
)
with check (
  exists (
    select 1 from public.employee_profiles employee
    where employee.auth_user_id = (select auth.uid())
      and employee.is_active = true
  )
);

create or replace function public.mw_touch_project_unit()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at := now();
  if new.handoff_status in ('Picked Up', 'Delivered') or new.status = 'Complete' then
    new.completed_at := coalesce(new.completed_at, now());
  elsif new.handoff_status not in ('Picked Up', 'Delivered') and new.status <> 'Complete' then
    new.completed_at := null;
  end if;
  return new;
end;
$$;

revoke all on function public.mw_touch_project_unit() from public, anon, authenticated;

drop trigger if exists mw_project_units_touch on public.project_units;
create trigger mw_project_units_touch
before insert or update on public.project_units
for each row execute function public.mw_touch_project_unit();

comment on table public.project_units is
  'Individually tracked deliverables within an outside project, including production and customer handoff.';
