create schema if not exists private;

create table if not exists private.project_financial_settings (
  id boolean primary key default true check (id),
  pin_hash text not null,
  allowed_profile_names text[] not null default array[]::text[],
  updated_at timestamptz not null default now()
);

create table if not exists private.project_financial_unlock_audit (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  employee_name text,
  success boolean not null,
  attempted_at timestamptz not null default now()
);

-- Configure the PIN hash and authorized profile names directly in each
-- deployment environment. Credentials must never be committed to source.

create or replace function public.verify_project_financial_pin(p_pin text)
returns boolean
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  employee_name text;
  setting private.project_financial_settings%rowtype;
  permitted boolean := false;
begin
  if auth.uid() is null then
    return false;
  end if;

  select lower(trim(display_name))
  into employee_name
  from public.employee_profiles
  where auth_user_id = auth.uid()
    and is_active = true
  limit 1;

  select * into setting
  from private.project_financial_settings
  where id = true;

  permitted := employee_name is not null
    and employee_name = any(setting.allowed_profile_names)
    and extensions.crypt(coalesce(p_pin, ''), setting.pin_hash) = setting.pin_hash;

  insert into private.project_financial_unlock_audit (auth_user_id, employee_name, success)
  values (auth.uid(), employee_name, permitted);

  return permitted;
end;
$$;

revoke all on function public.verify_project_financial_pin(text) from public, anon;
grant execute on function public.verify_project_financial_pin(text) to authenticated;

comment on function public.verify_project_financial_pin(text) is
  'Validates the project-financial screen PIN for specifically authorized active employees.';
