create table if not exists public.personal_follow_ups (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  owner_name text not null,
  title text not null,
  details text,
  note_type text not null default 'Task'
    check (note_type in ('Task', 'Callback', 'Reminder', 'General')),
  priority text not null default 'Normal'
    check (priority in ('Low', 'Normal', 'High', 'Urgent')),
  due_at timestamptz,
  status text not null default 'Open'
    check (status in ('Open', 'Completed')),
  related_project_id bigint references public.projects(id) on delete set null,
  created_by uuid not null default auth.uid() references auth.users(id),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.personal_follow_ups enable row level security;

grant select, insert, update, delete on public.personal_follow_ups to authenticated;
grant usage, select on sequence public.personal_follow_ups_id_seq to authenticated;
revoke all on public.personal_follow_ups from anon;

drop policy if exists "Staff can read assigned follow ups" on public.personal_follow_ups;
create policy "Staff can read assigned follow ups"
on public.personal_follow_ups for select
to authenticated
using (
  owner_user_id = (select auth.uid())
  or public.mw_calendar_is_administrator()
);

drop policy if exists "Staff can create assigned follow ups" on public.personal_follow_ups;
create policy "Staff can create assigned follow ups"
on public.personal_follow_ups for insert
to authenticated
with check (
  created_by = (select auth.uid())
  and (
    owner_user_id = (select auth.uid())
    or public.mw_calendar_is_administrator()
  )
  and exists (
    select 1
    from public.employee_profiles employee
    where employee.auth_user_id = owner_user_id
      and employee.is_active is true
  )
);

drop policy if exists "Staff can update assigned follow ups" on public.personal_follow_ups;
create policy "Staff can update assigned follow ups"
on public.personal_follow_ups for update
to authenticated
using (
  owner_user_id = (select auth.uid())
  or public.mw_calendar_is_administrator()
)
with check (
  owner_user_id = (select auth.uid())
  or public.mw_calendar_is_administrator()
);

drop policy if exists "Staff can delete assigned follow ups" on public.personal_follow_ups;
create policy "Staff can delete assigned follow ups"
on public.personal_follow_ups for delete
to authenticated
using (
  owner_user_id = (select auth.uid())
  or public.mw_calendar_is_administrator()
);

create index if not exists personal_follow_ups_owner_status_due_idx
  on public.personal_follow_ups (owner_user_id, status, due_at);

create index if not exists personal_follow_ups_project_idx
  on public.personal_follow_ups (related_project_id)
  where related_project_id is not null;
