create table if not exists public.customer_quote_approvals (
  id uuid primary key default gen_random_uuid(),
  quote_id bigint not null references public.project_quotes(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  token_hash text not null unique,
  document_version integer not null default 1 check (document_version > 0),
  document_hash text not null,
  document_snapshot jsonb not null,
  recipient_email text,
  status text not null default 'Sent' check (status in ('Sent', 'Viewed', 'Approved', 'Changes Requested', 'Declined', 'Expired', 'Revoked')),
  expires_at timestamptz not null,
  sent_at timestamptz not null default now(),
  viewed_at timestamptz,
  approved_at timestamptz,
  revoked_at timestamptz,
  signer_name text,
  signer_email text,
  signature_data_url text,
  acceptance_text text,
  signer_ip text,
  signer_user_agent text,
  customer_message text,
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customer_quote_approvals_quote_idx
  on public.customer_quote_approvals (quote_id, created_at desc);
create index if not exists customer_quote_approvals_status_idx
  on public.customer_quote_approvals (status, expires_at);

alter table public.customer_quote_approvals enable row level security;

create policy "Active employees can view quote approvals"
  on public.customer_quote_approvals for select
  to authenticated
  using (
    exists (
      select 1 from public.employee_profiles ep
      where ep.auth_user_id = (select auth.uid())
        and ep.is_active = true
    )
  );

revoke all on public.customer_quote_approvals from anon, authenticated;
grant select on public.customer_quote_approvals to authenticated;

create table if not exists public.customer_quote_approval_events (
  id bigint generated by default as identity primary key,
  approval_id uuid not null references public.customer_quote_approvals(id) on delete cascade,
  event_type text not null,
  event_detail jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists customer_quote_approval_events_approval_idx
  on public.customer_quote_approval_events (approval_id, occurred_at);

alter table public.customer_quote_approval_events enable row level security;

create policy "Active employees can view quote approval events"
  on public.customer_quote_approval_events for select
  to authenticated
  using (
    exists (
      select 1 from public.employee_profiles ep
      where ep.auth_user_id = (select auth.uid())
        and ep.is_active = true
    )
  );

revoke all on public.customer_quote_approval_events from anon, authenticated;
grant select on public.customer_quote_approval_events to authenticated;
