create table if not exists public.work_order_activity (
  id bigint generated by default as identity primary key,
  work_order_id bigint not null references public.work_orders(id) on delete cascade,
  production_job_id bigint references public.production_jobs(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  from_department text,
  to_department text,
  actor text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.work_order_activity enable row level security;

grant select, insert on public.work_order_activity to authenticated;
grant usage, select on sequence public.work_order_activity_id_seq to authenticated;
revoke update, delete on public.work_order_activity from anon, authenticated;

drop policy if exists "Active employees can read work order activity" on public.work_order_activity;
create policy "Active employees can read work order activity"
on public.work_order_activity for select
to authenticated
using (
  exists (
    select 1 from public.employee_profiles
    where employee_profiles.auth_user_id = (select auth.uid())
      and employee_profiles.is_active is true
  )
);

drop policy if exists "Active employees can record work order activity" on public.work_order_activity;
create policy "Active employees can record work order activity"
on public.work_order_activity for insert
to authenticated
with check (
  exists (
    select 1 from public.employee_profiles
    where employee_profiles.auth_user_id = (select auth.uid())
      and employee_profiles.is_active is true
  )
);

create index if not exists work_order_activity_job_created_idx
  on public.work_order_activity (production_job_id, created_at desc);
create index if not exists work_order_activity_order_created_idx
  on public.work_order_activity (work_order_id, created_at desc);

create or replace function public.mw_start_work_order_with_history(
  p_work_order_id bigint,
  p_actor text default null
)
returns public.work_orders
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_before public.work_orders%rowtype;
  v_result public.work_orders%rowtype;
begin
  select * into v_before
  from public.work_orders
  where id = p_work_order_id;

  v_result := public.mw_start_work_order(p_work_order_id, p_actor);

  insert into public.work_order_activity (
    work_order_id, production_job_id, event_type, from_status, to_status,
    from_department, to_department, actor, notes
  ) values (
    v_result.id, v_result.production_job_id, 'Started', v_before.status, v_result.status,
    v_before.department, v_result.department, nullif(trim(coalesce(p_actor, '')), ''),
    'Work started at ' || coalesce(v_result.step_name, v_result.department)
  );

  return v_result;
end;
$$;

create or replace function public.mw_complete_work_order_with_history(
  p_work_order_id bigint,
  p_actor text,
  p_completion_notes text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_before public.work_orders%rowtype;
  v_result jsonb;
begin
  if nullif(trim(coalesce(p_completion_notes, '')), '') is null then
    raise exception 'Enter a completion note before moving this work forward.';
  end if;

  select * into v_before
  from public.work_orders
  where id = p_work_order_id;

  v_result := public.mw_complete_work_order(p_work_order_id, p_actor);

  update public.work_orders
  set notes = concat_ws(E'\n', nullif(notes, ''), 'Completion note: ' || trim(p_completion_notes))
  where id = p_work_order_id;

  insert into public.work_order_activity (
    work_order_id, production_job_id, event_type, from_status, to_status,
    from_department, to_department, actor, notes
  ) values (
    v_before.id, v_before.production_job_id, 'Completed', v_before.status, 'Completed',
    v_before.department, v_result ->> 'next_department',
    nullif(trim(coalesce(p_actor, '')), ''), trim(p_completion_notes)
  );

  return v_result;
end;
$$;

create or replace function public.mw_bypass_work_order(
  p_work_order_id bigint,
  p_actor text,
  p_reason text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_before public.work_orders%rowtype;
  v_result jsonb;
  v_is_admin boolean;
begin
  select exists (
    select 1 from public.employee_profiles
    where auth_user_id = (select auth.uid())
      and is_active is true
      and lower(coalesce(access_level, '')) like '%admin%'
  ) into v_is_admin;

  if not v_is_admin then
    raise exception 'Administrator access is required to bypass a production station.';
  end if;

  if nullif(trim(coalesce(p_reason, '')), '') is null then
    raise exception 'Enter the reason for bypassing this station.';
  end if;

  select * into v_before
  from public.work_orders
  where id = p_work_order_id and is_active is true
  for update;

  if not found or v_before.status = 'Completed' then
    raise exception 'This work order can no longer be bypassed. Refresh the board.';
  end if;

  update public.work_orders
  set status = 'In Progress',
      started_at = coalesce(started_at, now()),
      notes = concat_ws(E'\n', nullif(notes, ''), 'ADMINISTRATOR BYPASS: ' || trim(p_reason))
  where id = p_work_order_id;

  v_result := public.mw_complete_work_order(p_work_order_id, p_actor);

  insert into public.work_order_activity (
    work_order_id, production_job_id, event_type, from_status, to_status,
    from_department, to_department, actor, notes
  ) values (
    v_before.id, v_before.production_job_id, 'Administrator Bypass', v_before.status, 'Completed',
    v_before.department, v_result ->> 'next_department',
    nullif(trim(coalesce(p_actor, '')), ''), trim(p_reason)
  );

  return v_result;
end;
$$;

revoke execute on function public.mw_start_work_order_with_history(bigint, text) from public, anon;
revoke execute on function public.mw_complete_work_order_with_history(bigint, text, text) from public, anon;
revoke execute on function public.mw_bypass_work_order(bigint, text, text) from public, anon;
grant execute on function public.mw_start_work_order_with_history(bigint, text) to authenticated;
grant execute on function public.mw_complete_work_order_with_history(bigint, text, text) to authenticated;
grant execute on function public.mw_bypass_work_order(bigint, text, text) to authenticated;
