alter table public.prequote_site_visits
  add column if not exists contact_email text,
  add column if not exists requested_visit_time time without time zone,
  add column if not exists access_instructions text,
  add column if not exists site_conditions text,
  add column if not exists measurements text,
  add column if not exists labor_requirements text,
  add column if not exists material_requirements text,
  add column if not exists customer_decisions text,
  add column if not exists recommended_next_step text,
  add column if not exists completed_by text;

create table if not exists public.prequote_site_visit_files (
  id bigint generated by default as identity primary key,
  visit_id uuid not null references public.prequote_site_visits(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  file_type text,
  file_size bigint,
  uploaded_by text,
  created_at timestamptz not null default now()
);

create index if not exists prequote_site_visit_files_visit_id_idx
  on public.prequote_site_visit_files (visit_id, created_at desc);

alter table public.prequote_site_visit_files enable row level security;

drop policy if exists "Active employees can view prequote visit files" on public.prequote_site_visit_files;
create policy "Active employees can view prequote visit files"
  on public.prequote_site_visit_files for select
  to authenticated
  using ((select public.mw_calendar_is_active_employee()));

drop policy if exists "Active employees can add prequote visit files" on public.prequote_site_visit_files;
create policy "Active employees can add prequote visit files"
  on public.prequote_site_visit_files for insert
  to authenticated
  with check ((select public.mw_calendar_is_active_employee()));

drop policy if exists "Administrators can delete prequote visit files" on public.prequote_site_visit_files;
create policy "Administrators can delete prequote visit files"
  on public.prequote_site_visit_files for delete
  to authenticated
  using (
    exists (
      select 1
      from public.employee_profiles profile
      where profile.auth_user_id = (select auth.uid())
        and profile.is_active is true
        and profile.access_level = 'Administrator'
    )
  );

revoke all on table public.prequote_site_visit_files from anon;
grant select, insert, delete on table public.prequote_site_visit_files to authenticated;
grant usage, select on sequence public.prequote_site_visit_files_id_seq to authenticated;
